package gui.mainGui.dialogs;

import static java.awt.Dialog.DEFAULT_MODALITY_TYPE;
import java.awt.Dimension;
import javax.swing.SpinnerNumberModel;
import risiko.game.GameProxy;

public class MoveDialog extends javax.swing.JDialog {

    private GameProxy game;
    private String toCountryName;
    private String fromCountryName;

    /**
     * Initialization.
     *
     * @param game
     * @param countryName
     */
    public MoveDialog(GameProxy game, String fromCountryName, String toCountryName) {
        initComponents();
        init(game, fromCountryName, toCountryName);
        labelInfo.setText("Da "+fromCountryName+" a "+toCountryName);
        int maxArmies = game.getMaxArmiesForMovement(fromCountryName);
        movementArmies.setModel(new SpinnerNumberModel(maxArmies, 1, maxArmies, 1));
    }

    public MoveDialog(GameProxy game, String fromCountryName, String toCountryName, String info, int minArmies) {
        initComponents();
        init(game, fromCountryName, toCountryName);
        
        this.fromCountryName = fromCountryName;
        this.toCountryName = toCountryName;
        int maxArmies = game.getMaxArmiesForMovement(fromCountryName);
        movementArmies.setModel(new SpinnerNumberModel(maxArmies, minArmies, maxArmies, 1));
        labelInfo.setText(info);
        this.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
    }

    private void init(GameProxy game, String fromCountryName, String toCountryName) {
        this.game = game;
        this.fromCountryName = fromCountryName;
        this.toCountryName = toCountryName;
        Dimension dim = getToolkit().getScreenSize();
        this.setLocation(dim.width / 2 - this.getWidth() / 2, dim.height / 2 - this.getHeight() / 2);
        this.setModalityType(DEFAULT_MODALITY_TYPE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelInfo = new javax.swing.JLabel();
        movementText = new javax.swing.JLabel();
        movementArmies = new javax.swing.JSpinner();
        execute = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        movementText.setText("Quante armate vuoi spostare");

        execute.setText("esegui");
        execute.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                executeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 25, Short.MAX_VALUE)
                        .addComponent(movementText)
                        .addGap(18, 18, 18)
                        .addComponent(movementArmies, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(execute, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(labelInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(movementText, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(movementArmies, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(execute))
                .addGap(60, 60, 60))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void executeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_executeActionPerformed
        game.move(fromCountryName, toCountryName, (Integer) movementArmies.getValue());
        MoveDialog.this.dispose();
    }//GEN-LAST:event_executeActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton execute;
    private javax.swing.JLabel labelInfo;
    private javax.swing.JSpinner movementArmies;
    private javax.swing.JLabel movementText;
    // End of variables declaration//GEN-END:variables
}
